[book]
authors = ["Bram"]
language = "en"
multilingual = false
src = "src"
title = "Vi-IMproved"
description = "vim help and manuals "

[output.html]
theme = "src/theme"
git-repository-url = "https://github.com/ashutoshmjain/vim"
cname = "ceremonies.shutri.com"
edit-url-template = "https://github.com/ashutoshmjain/vim/edit/main/{path}"
no-section-label = true

[output.html.print]
enable = true    # include support for printable output


